services:
  webapp:
    build:
      context: .
      dockerfile: ProdTemplate.Api/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:8080"
      - "8080:8080"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "8050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 1s
      timeout: 10s
      retries: 5
      
volumes:
  postgres_data: